name: Update Registry (On Merge)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip update')"
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Execute py script
        run: |
          python -m pip install --upgrade pip
          pip install pandas pyyaml projectcard
          pip install -e git+https://github.com/network-wrangler/network_wrangler.git@main#egg=network_wrangler
          python update_registry.py

      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]"
          git config --local user.name "github-actions[bot]@users.noreply.github.com"
          git add -A
          # Only commits if there are changes (e.g., CSV updated or YAMLs renumbered)
          git diff --quiet && git diff --staged --quiet || git commit -m "Automated registry and ID sync"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main